version: "3.7" 
services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html/"
      - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php
      # - mysql_db
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html/"
    # command: php -S 0.0.0.0:9000 -t public/
    # links:
      # - mysql
    depends_on:
      - mysql_db
  mysql_db:
    container_name: mysql_db
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9906:3306"
    # volumes:
    #   - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'MYSQL_DATABASE'
      # MYSQL_USER: 'MYSQL_USER'
      # MYSQL_PASSWORD: 'MYSQL_PASSWORD'
      MYSQL_ROOT_PASSWORD: 'MYSQL_ROOT_PASSWORD'
    command: --default-authentication-plugin=mysql_native_password
    # command:
    #   - /bin/bash
    #   - -c 
    # #   - mysql -uroot -pMYSQL_ROOT_PASSWORD -e "alter user 'MYSQL_USER'@'%' identified with mysql_native_password by 'MYSQL_PASSWORD';"
# volumes:
#   mysql:
