version: "3.7" 
services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html/"
      - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php

  nginx_2:
    image: nginx:1.17.3
    container_name: nginx_2
    ports:
      - "8081:80"
    volumes:
      - "./frontend:/usr/share/nginx/html"
  
  nginx_3:
    image: nginx:1.17.3
    container_name: nginx_3
    ports:
      - "8082:80"
    volumes:
      - "./backoffice/build:/usr/share/nginx/html"

  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html/"
    depends_on:
      - mysql_db

  mysql_db:
    container_name: mysql_db
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: 'MYSQL_DATABASE'

      MYSQL_ROOT_PASSWORD: 'MYSQL_ROOT_PASSWORD'
    command: --default-authentication-plugin=mysql_native_password

