version: "3.7" 
services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html/"
      - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php
      - database
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html/"
    # command: php -S 0.0.0.0:9000 -t public/
    # links:
      # - mysql
    depends_on:
      - database
  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3307:3306"
    # volumes:
    #   - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'MYSQL_DATABASE'
      MYSQL_USER: 'MYSQL_USER'
      MYSQL_PASSWORD: 'MYSQL_PASSWORD'
      MYSQL_ROOT_PASSWORD: 'MYSQL_ROOT_PASSWORD'
# volumes:
#   mysql:
