use MYSQL_DATABASE;
CREATE TABLE Politicos (ID INT, Titulo VARCHAR(255), Nome VARCHAR(255), Partido VARCHAR(255), Foto VARCHAR(255), Votos INT, Vice LONGTEXT);
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (0, 'prefeito', 'BRANCO', '', '', 0, '');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (0, 'vereador', 'BRANCO', '', '', 0, '');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (-1, 'prefeito', 'NULO', '', '', 0, '');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (-1, 'vereador', 'NULO', '', '', 0, '');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (51222, 'vereador', 'Christianne Varao', 'PEN', 'cv1.jpg', 0, '{}');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (55555, 'vereador', 'Homero do Ze Filho', 'PSL', 'cv2.jpg', 0, '{}');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (43333, 'vereador', 'Dandor', 'PV', 'cv3.jpg', 0, '{}');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (15123, 'vereador', 'Filho', 'MDB', 'cv4.jpg', 0, '{}');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (27222, 'vereador', 'Joel Varao', 'PSDC', 'cv5.jpg', 0, '{}');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (45000, 'vereador', 'Professor Clebson Almeida', 'PSDB', 'cv6.jpg', 0, '{}');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (12, 'prefeito', 'Chiquinho do Adbon', 'PDT', 'cp3.jpg', 0, '{"nome": "Ar\u00e3o", "partido": "PRP", "foto": "v3.jpg"}');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (15, 'prefeito', 'Malrinete Gralhada', 'MDB', 'cp2.jpg', 0, '{"nome": "Biga", "partido": "MDB", "foto": "v2.jpg"}');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (45, 'prefeito', 'Dr. Francisco', 'PSC', 'cp1.jpg', 0, '{"nome": "Jo\u00e3o Rodrigues", "partido": "PV", "foto": "v1.jpg"}');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (54, 'prefeito', 'Ze Lopes', 'PPL', 'cp4.jpg', 0, '{"nome": "Francisca Ferreira Ramos", "partido": "PPL", "foto": "v4.jpg"}');
INSERT INTO Politicos (ID, Titulo, Nome, Partido, Foto, Votos, Vice) VALUES (65, 'prefeito', 'Lindomar Pescador', 'PC do B', 'cp5.jpg', 0, '{"nome": "Malu", "partido": "PC do B", "foto": "v5.jpg"}');
CREATE TABLE Eleicao (ID INT, Status BOOLEAN);
INSERT INTO Eleicao (ID, Status) VALUES (0, true);
